### ISSUE TITLE
Please add blogspot.sg to GFWlist

### ISSUE THREAD

**Issue by hubanya** [koolshare/koolshare.github.io#134]
Please add blogspot.sg to GFWlist.

I submitted google.com.sg, when are you going to add it? 

Thanks!

**Comment by tianshi1987** [comment]
you can add it in whitelist,

2016-08-08 11:10 GMT+08:00 hubanya <notifications@github.com>:

**Comment by hubanya** [comment]
I'm completely confused. It is blocked by GFW. Why should I add it to whitelist? Do you mean GFWlist? 

Yes I could. 

But it seems to me no one is maintaining the GFWList, is it correct?

Thanks.

**Comment by sadoneli** [comment]
the gfwlist is maintained by [https://github.com/gfwlist/gfwlist](this project), you can response the blocked domain there.

**Comment by hubanya** [comment]
I'm confused again. It seems to me gfwlist used by xiaobao firmware is not the one in https://github.com/gfwlist/gfwlist. For example, google.com.sg is in the later but not in koolshare's gfwlist. Maybe this gfwlist is carefully filtered for use on routers?

Moreover, in the shadowsocks section in xiaobao firmware, it is particularly mentioned that users can submit blocked domains to THIS project for your maintenance.

Thanks..

**Comment by sadoneli** [comment]
Yes, not exactly. accturally, after batch regular expression treat, only `google.com` left, we add `google.com.hk` by ourself, as you mentioned  `google.com.sg`, I will add it in the gfwlist.conf.
I recommend you response `blogspot.sg` to the offical gfwlist, they have more professional test to go through before add it to the list. If the add it, we will merge the official gfwlist.
For the time been, you can easily add this doamin into the balck domian.

Due to the limited energy, we don't have much time to test every suspect domain on each isp and region in China. If you interested, you are welcome to join us and make some help on this project.

**Comment by hubanya** [comment]
Thanks a lot for your clarification!

I finally understand!

I really appreciate your efforts!
